server:
  port: 9013
spring:
  application:
    name: tensquare-encrypt
zuul:
  routes:
    tensquare-article: #文章微服务
      path: /article/** #配置请求URL的请求规则，所有以 /article开头的请求 都交给文章微服务处理
      serviceId: tensquare-article #指定Eureka注册中心中的服务id
      strip-prefix: true  # 过滤规则 当请求来的时候localhost:9013/article/article/search---> localhost:9004/article/search
      sentiviteHeaders:
      customSensitiveHeaders: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true